server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    import: "classpath:env/.env.properties"

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

      logging:
        level:
          org:
            hibernate:
              SQL: debug
              type: trace


jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRE}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRE}


